---
version: 2
updates:
  - package-ecosystem: terraform
    directory: /modules/aws/deployment_bucket
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/dynamodb
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/mail
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/deployment_bucket
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/dynamodb
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/mail
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/acm_certificate
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/central_logs
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/github_oidc
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/http_api
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/lambda
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/lambda-at-edge
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/static_site
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /modules/aws/vpc
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/acm_certificate
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/central_logs
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/github_oidc
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/http_api
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/lambda
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/lambda-at-edge
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/static_site
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /examples/aws/vpc
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - terraform
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
