---
name: ci_validate_yaml

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - '.yamllint.yml'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '.yamllint.yml'

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) && 'ubuntu-latest' || 'littlemonarch' }}
    steps:
      - uses: actions/checkout@v7

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
          file_or_dir: .
          strict: false
